---
title: "RewardAnalysis"
author: "Benjamin Evans"
date: "22/04/2022"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# knitr::opts_chunk$set(echo = TRUE)

data = read.csv("DataTable.csv")

library(ggplot2)
library(dplyr)
library(tidyr)
library(knitr)
library(kableExtra)

```

# All Tests




```{r}
d_table = data %>%
  select(map_name, set_n, path, avg_times, success_rate)%>%
  arrange(path)

kbl(d_table, format="markdown")
# a = kbl(d_table, format="latex")
# print(a)
```


## Benchmark



```{r, comment=NA}
data1 = data %>%
  filter(test_name=='BaselineDRL_r')%>%
  filter(map_name!='levine_blocked')%>%
  filter(avg_times>0)%>%
  select(map_name, path, avg_times)%>%
  group_by(map_name)%>%
  # pivot_wider(names_from = map_name, values_from = avg_times)%>%
  summarise(min = min(avg_times, na.rm=TRUE), mean = mean(avg_times, na.rm=TRUE))

rownames(data1) = data1$map_name
d1 = t(data1)
d1 = data.frame(d1)
d1 = d1[-c(1),]

d1 = d1[, order(names(d1))]

kbl(d1)

a = kbl(d1, format="latex", booktabs = T)%>%
  column_spec(2, width="3cm")%>%
  column_spec(3, width="3cm")%>%
  column_spec(4, width="3cm")
  # column_spec(5, width="3cm")
print(a)

```
```{r}

d_table2 = data %>%
  filter(test_name=="FGM"| test_name=='PP')%>%
  select(map_name, path, avg_times)%>%
  pivot_wider(names_from = map_name, values_from = avg_times)
  # arrange(set_n)

rownames(d_table2) = d_table2$path
# d2 = d_table2
d2 = d_table2[,-c(1)]
rownames(d2) = c("FGM", "PP")
d2 = d2[, order(names(d2))]
kbl(d2)

# d3 = rbind(d1, d2)
# 
# kbl(d3)

```

```{r, comment=NA}
d_table = data %>%
  filter(test_name=="FGM"| test_name=='PP'|test_name=='BaselineDRL')%>%
  # filter(map_name!='porto'&map_name!='berlin'&map_name!='berlin')%>%
  select(map_name, path, avg_times)%>%
  pivot_wider(names_from = map_name, values_from = avg_times)
  # arrange(set_n)

a = kbl(d_table, format="latex", booktabs = T)%>%
  column_spec(2, width="3cm")%>%
  column_spec(3, width="3cm")%>%
  column_spec(4, width="3cm")
print(a)
# stargazer(d_table[1:2,], summary=FALSE)
# print(stargazer(d_table[1:2,], summary=FALSE),  file="BenchmarkTable.tex")
```

### Repeat

```{r, comment=NA}
data %>%
  filter(test_name=='BaselineDRL_r')%>%
  filter(avg_times>0)%>%
  select(map_name, n, path, avg_times)%>%
  ggplot(aes(x=map_name, y=avg_times))+
  geom_boxplot(colour="blue3", lwd=1, outlier.shape=NA)+
  ylab("Average Lap-times")+
  xlab("Map Name")+ 
  ylim(0, 160)+
  geom_point(color="forestgreen", size=4)+
  # theme_bw(base_line_size=1)
  theme_linedraw()
  # geom_point(aes(y=mean(avg_times)), shape=4, size=10)

ggsave("BaselineRepeatBoxplot.pdf", width=6, height=4)

```

```{r, comment=NA}
zero = data %>%
  filter(test_name=='BaselineDRL_r')%>%
  filter(avg_times==0)%>%
  select(map_name, n, path, avg_times)

kbl(zero)
  
```

## Baseline Tests


```{r}
d_table = data %>%
  filter(reward_name=="Baseline")%>%
  select(map_name, path, avg_times, r_bias)%>%
  pivot_wider(names_from = map_name, values_from = avg_times)%>%
  arrange(r_bias)

print(kable(d_table, format="latex"))
```



## Distance

```{r}
d_table = data %>%
  filter(reward_name=="Distance")%>%
  select(map_name, path, set_n, b_distance, avg_times, success_rate)%>%
  # pivot_wider(names_from = map_name, values_from = avg_times)%>%
  arrange(set_n, b_distance) 
  # arrange(b_distance)

kable(d_table)
```
```{r}
data %>%
  filter(reward_name=="Distance"& map_name=="columbia_small")%>%
  select(b_distance, avg_times)%>%
  ggplot(aes(x=b_distance, y=avg_times))+
  geom_point()
  
  
```

## Baseline repeat


```{r}
d_table = data %>%
  filter(reward_name=="BaselineRepeat"&set_n==4)%>%
  select(map_name, path, avg_times, n)%>%
  pivot_wider(names_from = map_name, values_from = avg_times)%>%
  arrange(n)

kable(d_table)
```

```{r}
data %>%
  filter(reward_name=="BaselineRepeat")%>%
  select(map_name, path, avg_times, n)%>%
  # pivot_wider(names_from = map_name, values_from = avg_times)%>%
  ggplot(aes(x=map_name, y=avg_times))+
  geom_boxplot()


```

## Speed Test
```{r}
d_table = data %>%
  filter(test_name=="SpeedTests" & n==0)%>%
  select(map_name, path, avg_times, set_n)%>%
  pivot_wider(names_from = map_name, values_from = avg_times)%>%
  arrange(set_n)

kable(d_table)
```

```{r}
data %>%
  filter(test_name=="SpeedTests")%>%
  select(map_name, path, avg_times, n)%>%
  # pivot_wider(names_from = map_name, values_from = avg_times)%>%
  ggplot(aes(x=map_name, y=avg_times))+
  geom_boxplot()


```


## Algorithm Test
```{r}
d_table = data %>%
  filter(test_name=="AlgorithmTests" & set_n==3 )%>%
  select(map_name, path, avg_times, discrete, n)%>%
  pivot_wider(names_from = map_name, values_from = avg_times)%>%
  # pivot_wider(names_from = discrete, values_from = avg_times)%>%
  arrange(n)

kable(d_table)
```

```{r}
data %>%
  filter(test_name=="AlgorithmTests" & set_n==3& avg_times> 1.0)%>%
  select(map_name, path, avg_times, discrete)%>%
  # pivot_wider(names_from = map_name, values_from = avg_times)%>%
  ggplot(aes(x=map_name, y=avg_times, fill=factor(discrete)))+
  geom_boxplot()


```

```{r}
d_table = data %>%
  filter(test_name=="AlgorithmTests" & set_n==3  )%>%
  select(map_name, avg_times, discrete)%>%
  pivot_wider(names_from = map_name, values_from = avg_times)
  # group_by(map_name)%>%
  # mutate(zero_count=length(which(avg_times==0)))%>%
  # select(discrete)

print(summarise(d_table))

kable(d_table)
```

